name: harpy_example
description: Example application using the Harpy framework
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  harpy:
    path: ../

dev_dependencies:
  lints: ^3.0.0