name: harpy
description: A modern, fast, and lightweight backend framework for Dart
version: 0.1.0
homepage: https://moses-team.ru
repository: https://github.com/moses-team-ru/harpy

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  collection: ^1.19.1
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

executables:
  harpy: